---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    provisioner: 
      solo_rb:
        environment: opsworks
    run_list:
      - recipe[drupal-varnish::default]
    attributes:
